"""Release-controlled metadata for official transcription models.

This module is deliberately source-controlled rather than generated by the
installer.  Updating an official model is a release action: review the upstream
revision and file hashes here, then ship the changed application.
"""

from __future__ import annotations

from dataclasses import dataclass
from types import MappingProxyType
from typing import Mapping


@dataclass(frozen=True)
class OfficialModelSpec:
    model_id: str
    repository_id: str
    revision: str
    files: Mapping[str, str]


# This is the exact large-v3-turbo artifact already used for the supported
# Windows release.  Hashes cover every file passed to faster-whisper, not a
# manifest emitted after a user-controlled download.
_LARGE_V3_TURBO = OfficialModelSpec(
    model_id="large-v3-turbo",
    repository_id="mobiuslabsgmbh/faster-whisper-large-v3-turbo",
    revision="0a363e9161cbc7ed1431c9597a8ceaf0c4f78fcf",
    files=MappingProxyType(
        {
            "config.json": "b0253ea6c0d3bea6b1e19e91a02acfd3b53f4467362efcb5a3e6b16c9b3a9b7e",
            "model.bin": "e76620f83d5f5b69efd3d87e3dc180c1bd21df9fbebacfd4335e5e1efcc018da",
            "preprocessor_config.json": "7ccc62c6f2765af1f3b46c00c9b5894426835a05021c8b9c01eecb6dfb542711",
            "tokenizer.json": "297b13372ac43916285644fb9687add3cc62ee2a1adb60da3dc25cc94c1871fd",
            "vocabulary.json": "c69260f2ab26d659b7c398f9a2b2b48ed0df16c3b47d7326782fd9cba71690c1",
        }
    ),
)


OFFICIAL_MODELS: Mapping[str, OfficialModelSpec] = MappingProxyType(
    {_LARGE_V3_TURBO.model_id: _LARGE_V3_TURBO}
)


def available_model_ids() -> tuple[str, ...]:
    return tuple(OFFICIAL_MODELS)


def get_official_model_spec(model_id: str) -> OfficialModelSpec:
    try:
        return OFFICIAL_MODELS[model_id]
    except KeyError as exc:
        raise ValueError("Model is not approved for this release.") from exc
